# Generated by Django 6.0 on 2025-12-04 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('stage', models.IntegerField(blank=True, null=True)),
                ('list_id', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client_campaign_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='campaigns.clientcampaignmodel')),
                ('response_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='campaigns.responsecategory')),
                ('voice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='campaigns.voice')),
            ],
            options={
                'verbose_name': 'Call Record',
                'verbose_name_plural': 'Call Records',
                'db_table': 'calls',
                'indexes': [models.Index(fields=['client_campaign_model'], name='idx_call_ccm'), models.Index(fields=['number'], name='idx_calls_number'), models.Index(fields=['timestamp'], name='idx_calls_timestamp'), models.Index(fields=['stage'], name='idx_calls_stage'), models.Index(fields=['list_id'], name='idx_calls_list_id'), models.Index(fields=['voice'], name='idx_calls_voice'), models.Index(fields=['response_category'], name='idx_calls_response_cat')],
            },
        ),
    ]
