# Generated by Django 6.0 on 2025-12-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='transferred',
            field=models.BooleanField(default=False),
        ),
    ]
