# Generated by Django 6.0 on 2025-12-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='idx_clients_is_archived',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_archived',
        ),
    ]
