# Generated by Django 6.0 on 2025-12-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_idx_clients_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assembly_api_key',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
