# Generated by Django 6.0 on 2025-12-22 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_assembly_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='clients.client')),
                ('user', models.OneToOneField(limit_choices_to={'role__name': 'client_member'}, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Employee',
                'verbose_name_plural': 'Client Employees',
                'db_table': 'client_employees',
                'indexes': [models.Index(fields=['client'], name='idx_client_emp_client'), models.Index(fields=['user'], name='idx_client_emp_user')],
                'unique_together': {('client', 'user')},
            },
        ),
    ]
