# Generated by Django 6.0 on 2026-01-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='plain_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
