# Generated by Django 6.0 on 2026-01-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='plain_password',
        ),
    ]
