# Generated by Django 6.0 on 2025-12-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('client_member', 'Client Member'), ('onboarding', 'Onboarding'), ('qa', 'QA')], max_length=50, unique=True),
        ),
    ]
