# Generated by Django 6.0 on 2025-12-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_number', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Extension',
                'verbose_name_plural': 'Extensions',
                'db_table': 'extensions',
                'indexes': [models.Index(fields=['extension_number'], name='idx_ext_number')],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'db_table': 'servers',
                'indexes': [models.Index(fields=['ip'], name='idx_servers_ip'), models.Index(fields=['alias'], name='idx_servers_alias')],
            },
        ),
    ]
