# Generated by Django 6.0 on 2025-12-04 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '__first__'),
        ('infrastructure', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaigns',
                'indexes': [models.Index(fields=['name'], name='idx_campaigns_name')],
            },
        ),
        migrations.CreateModel(
            name='CampaignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_models', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Campaign-Model Pair',
                'verbose_name_plural': 'Campaign-Model Pairs',
                'db_table': 'campaign_model',
            },
        ),
        migrations.CreateModel(
            name='CampaignRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('long_call_scripts_active', models.BooleanField(default=False)),
                ('disposition_set', models.TextField(blank=True, null=True)),
                ('bot_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Campaign Requirement',
                'verbose_name_plural': 'Campaign Requirements',
                'db_table': 'campaign_requirements',
                'indexes': [models.Index(fields=['name'], name='idx_campaign_requirements_name')],
            },
        ),
        migrations.CreateModel(
            name='CloserDialer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_validation_link', models.CharField(blank=True, max_length=500, null=True)),
                ('admin_link', models.CharField(blank=True, max_length=500, null=True)),
                ('admin_username', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_password', models.CharField(blank=True, max_length=255, null=True)),
                ('closer_campaign', models.CharField(max_length=255)),
                ('ingroup', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=5060)),
            ],
            options={
                'verbose_name': 'Closer Dialer',
                'verbose_name_plural': 'Closer Dialers',
                'db_table': 'closer_dialer',
                'indexes': [models.Index(fields=['port'], name='idx_closer_dialer_port')],
            },
        ),
        migrations.CreateModel(
            name='DialerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closer_dialer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dialer_settings', to='campaigns.closerdialer')),
            ],
            options={
                'verbose_name': 'Dialer Settings',
                'verbose_name_plural': 'Dialer Settings',
                'db_table': 'dialer_settings',
            },
        ),
        migrations.CreateModel(
            name='ClientCampaignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('custom_comments', models.TextField(blank=True, null=True)),
                ('current_remote_agents', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('campaign_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='client_associations', to='campaigns.campaignmodel')),
                ('campaign_requirements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_campaigns', to='campaigns.campaignrequirements')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_models', to='clients.client')),
                ('dialer_settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_campaigns', to='campaigns.dialersettings')),
            ],
            options={
                'verbose_name': 'Client Campaign',
                'verbose_name_plural': 'Client Campaigns',
                'db_table': 'client_campaign_model',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('transfer_settings', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
                'db_table': 'models',
                'indexes': [models.Index(fields=['name'], name='idx_models_name')],
            },
        ),
        migrations.AddField(
            model_name='campaignmodel',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='campaign_models', to='campaigns.model'),
        ),
        migrations.CreateModel(
            name='PrimaryDialer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_validation_link', models.CharField(blank=True, max_length=500, null=True)),
                ('admin_link', models.CharField(blank=True, max_length=500, null=True)),
                ('admin_username', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_password', models.CharField(blank=True, max_length=255, null=True)),
                ('fronting_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('verifier_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(default=5060)),
            ],
            options={
                'verbose_name': 'Primary Dialer',
                'verbose_name_plural': 'Primary Dialers',
                'db_table': 'primary_dialer',
                'indexes': [models.Index(fields=['port'], name='idx_primary_dialer_port')],
            },
        ),
        migrations.AddField(
            model_name='dialersettings',
            name='primary_dialer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dialer_settings', to='campaigns.primarydialer'),
        ),
        migrations.CreateModel(
            name='ResponseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Response Category',
                'verbose_name_plural': 'Response Categories',
                'db_table': 'response_categories',
                'indexes': [models.Index(fields=['name'], name='idx_response_categories_name')],
            },
        ),
        migrations.CreateModel(
            name='ServerCampaignBots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_count', models.IntegerField(default=0)),
                ('client_campaign_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_bots', to='campaigns.clientcampaignmodel')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_bots', to='infrastructure.extension')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_bots', to='infrastructure.server')),
            ],
            options={
                'verbose_name': 'Server Campaign Bot',
                'verbose_name_plural': 'Server Campaign Bots',
                'db_table': 'server_campaign_bots',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'db_table': 'status',
                'indexes': [models.Index(fields=['status_name'], name='idx_status_status_name'), models.Index(fields=['updated_at'], name='idx_status_updated_at')],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='history', to='campaigns.status')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status History',
                'db_table': 'status_history',
            },
        ),
        migrations.AddField(
            model_name='clientcampaignmodel',
            name='status_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_campaigns', to='campaigns.statushistory'),
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Voice',
                'verbose_name_plural': 'Voices',
                'db_table': 'voices',
                'indexes': [models.Index(fields=['name'], name='idx_voices_name')],
            },
        ),
        migrations.AddIndex(
            model_name='campaignmodel',
            index=models.Index(fields=['campaign'], name='idx_campaign_model_campaign_id'),
        ),
        migrations.AddIndex(
            model_name='campaignmodel',
            index=models.Index(fields=['model'], name='idx_campaign_model_model_id'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignmodel',
            unique_together={('campaign', 'model')},
        ),
        migrations.AddIndex(
            model_name='dialersettings',
            index=models.Index(fields=['primary_dialer'], name='idx_ds_primary'),
        ),
        migrations.AddIndex(
            model_name='dialersettings',
            index=models.Index(fields=['closer_dialer'], name='idx_ds_closer'),
        ),
        migrations.AddIndex(
            model_name='servercampaignbots',
            index=models.Index(fields=['client_campaign_model'], name='idx_scb_ccm'),
        ),
        migrations.AddIndex(
            model_name='servercampaignbots',
            index=models.Index(fields=['server'], name='idx_scb_server'),
        ),
        migrations.AddIndex(
            model_name='servercampaignbots',
            index=models.Index(fields=['extension'], name='idx_scb_extension'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['status'], name='idx_status_history_status_id'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['start_date'], name='idx_status_history_start_date'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['end_date'], name='idx_status_history_end_date'),
        ),
        migrations.AddIndex(
            model_name='clientcampaignmodel',
            index=models.Index(fields=['client'], name='idx_ccm_client'),
        ),
        migrations.AddIndex(
            model_name='clientcampaignmodel',
            index=models.Index(fields=['campaign_model'], name='idx_ccm_camp_model'),
        ),
        migrations.AddIndex(
            model_name='clientcampaignmodel',
            index=models.Index(fields=['is_active'], name='idx_ccm_active'),
        ),
        migrations.AddIndex(
            model_name='clientcampaignmodel',
            index=models.Index(fields=['is_enabled'], name='idx_ccm_enabled'),
        ),
        migrations.AddIndex(
            model_name='clientcampaignmodel',
            index=models.Index(fields=['start_date'], name='idx_ccm_start'),
        ),
        migrations.AddIndex(
            model_name='clientcampaignmodel',
            index=models.Index(fields=['end_date'], name='idx_ccm_end'),
        ),
    ]
