# Generated by Django 6.0 on 2025-12-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrequirements',
            name='disposition_set',
            field=models.BooleanField(default=False),
        ),
    ]
