# Generated by Django 6.0 on 2025-12-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaignrequirements_disposition_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsecategory',
            name='color',
            field=models.CharField(default='#10B981', max_length=255),
            preserve_default=False,
        ),
    ]
