# Generated by Django 6.0 on 2025-12-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_responsecategory_color'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dialersettings',
            name='idx_ds_primary',
        ),
        migrations.AddField(
            model_name='clientcampaignmodel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dialersettings',
            name='primary_dialers',
            field=models.ManyToManyField(related_name='dialer_settings', to='campaigns.primarydialer'),
        ),
        migrations.AddIndex(
            model_name='clientcampaignmodel',
            index=models.Index(fields=['approved'], name='idx_ccm_approved'),
        ),
        migrations.RemoveField(
            model_name='dialersettings',
            name='primary_dialer',
        ),
    ]
