# Generated by Django 6.0 on 2025-12-10 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_dialersettings_idx_ds_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialersettings',
            name='primary_dialers',
        ),
        migrations.AddField(
            model_name='primarydialer',
            name='dialer_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_dialers', to='campaigns.dialersettings'),
        ),
        migrations.AddIndex(
            model_name='primarydialer',
            index=models.Index(fields=['dialer_settings'], name='idx_primary_dialer_settings'),
        ),
    ]
