# Generated by Django 6.0 on 2025-12-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_remove_dialersettings_primary_dialers_and_more'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clientcampaignmodel',
            name='idx_ccm_approved',
        ),
        migrations.RenameField(
            model_name='clientcampaignmodel',
            old_name='approved',
            new_name='is_approved',
        ),
        migrations.AddIndex(
            model_name='clientcampaignmodel',
            index=models.Index(fields=['is_approved'], name='idx_ccm_approved'),
        ),
    ]
