# Generated by Django 6.0 on 2025-12-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_remove_clientcampaignmodel_idx_ccm_approved_and_more'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaignrequirements',
            name='idx_campaign_requirements_name',
        ),
        migrations.RemoveField(
            model_name='clientcampaignmodel',
            name='campaign_requirements',
        ),
        migrations.AddField(
            model_name='clientcampaignmodel',
            name='bot_count',
            field=models.IntegerField(default=0, help_text='Number of bots for this campaign'),
        ),
        migrations.AddField(
            model_name='clientcampaignmodel',
            name='disposition_set',
            field=models.BooleanField(default=False, help_text='Is disposition set configured?'),
        ),
        migrations.AddField(
            model_name='clientcampaignmodel',
            name='long_call_scripts_active',
            field=models.BooleanField(default=False, help_text='Are long call scripts active?'),
        ),
        migrations.AddIndex(
            model_name='clientcampaignmodel',
            index=models.Index(fields=['bot_count'], name='idx_ccm_bot_count'),
        ),
        migrations.DeleteModel(
            name='CampaignRequirements',
        ),
    ]
