# Generated by Django 6.0 on 2025-12-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_transfersettings_alter_model_transfer_settings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfersettings',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Transfer Setting', 'verbose_name_plural': 'Transfer Settings'},
        ),
        migrations.AddField(
            model_name='transfersettings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfersettings',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which to display (lower = first)'),
        ),
        migrations.AddField(
            model_name='transfersettings',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfersettings',
            name='quality_score',
            field=models.IntegerField(default=50, help_text='Quality score out of 100'),
        ),
        migrations.AddField(
            model_name='transfersettings',
            name='volume_score',
            field=models.IntegerField(default=50, help_text='Volume score out of 100'),
        ),
        migrations.AddIndex(
            model_name='transfersettings',
            index=models.Index(fields=['display_order'], name='idx_transfer_settings_order'),
        ),
    ]
