# Generated by Django 6.0 on 2025-12-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_alter_transfersettings_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='model',
            name='idx_models_transfer_settings',
        ),
        migrations.RemoveField(
            model_name='model',
            name='transfer_settings',
        ),
        migrations.AddField(
            model_name='model',
            name='transfer_settings',
            field=models.ManyToManyField(blank=True, related_name='models', to='campaigns.transfersettings'),
        ),
    ]
