# Generated by Django 6.0 on 2025-12-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_remove_model_idx_models_transfer_settings_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clientcampaignmodel',
            name='idx_ccm_enabled',
        ),
        migrations.RemoveIndex(
            model_name='clientcampaignmodel',
            name='idx_ccm_approved',
        ),
        migrations.RemoveField(
            model_name='clientcampaignmodel',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='clientcampaignmodel',
            name='is_enabled',
        ),
    ]
