# Generated by Django 6.0 on 2025-12-19 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_remove_clientcampaignmodel_idx_ccm_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statushistory',
            options={'ordering': ['-start_date'], 'verbose_name': 'Status History', 'verbose_name_plural': 'Status History'},
        ),
        migrations.RemoveField(
            model_name='clientcampaignmodel',
            name='status_history',
        ),
        migrations.AddField(
            model_name='statushistory',
            name='client_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='campaigns.clientcampaignmodel'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['client_campaign'], name='idx_status_history_campaign_id'),
        ),
    ]
