# Generated by Django 6.0 on 2025-12-22 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_alter_statushistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmodel',
            name='selected_transfer_setting',
            field=models.ForeignKey(blank=True, help_text='The specific transfer setting selected for this client campaign', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='client_campaigns_using', to='campaigns.transfersettings'),
        ),
    ]
