# Generated by Django 6.0 on 2026-01-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_remove_campaignmodel_selected_transfer_setting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcampaignmodel',
            name='is_active',
        ),
    ]
