# Generated by Django 6.0 on 2026-01-15 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_remove_clientcampaignmodel_is_active'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clientcampaignmodel',
            name='idx_ccm_active',
        ),
    ]
